adonisjs/v6-docs

content/docs/guides/installation.md
N/A
This PR sets the minimum node version to 20.6, which is the minimum version of node that supports `module.register`. https://nodejs.org/dist/latest-v20.x/docs/api/module.html#moduleregisterspecifier-parenturl-options
Using a older version will prevent you from running ace with the following error:
```
node ace.js
file:///Users/nicolas/Code/hello-world/ace.js:17
import { register } from 'node:module'
^^^^^^^^
SyntaxError: The requested module 'node:module' does not provide an export named 'register'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
at async DefaultModuleLoader.import (node:internal/modules/esm/loader:246:24)
at async loadESM (node:internal/process/esm_loader:40:7)
at async …
```
=> fix: incorrect minimum node version

content/docs/auth/introduction.md
```sh
node ace configure @adonisjs/auth --guard=tokens                                                                          ✘ 1 migrate-adonisjs-to-v6-from-scratch ✭ ◼
[ error ] The selected guard "tokens" is invalid. Select one from: session, access_tokens
```
=> docs(Auth): fix token name

content/docs/reference/edge.md
I found there is a typo error in the Edge.js reference documentation.
Instead of `@inputError`, the documentation mentions `@error`.
This PR fix this.
I did not create any issue before this PR as the fix very small. I did not want to clutter the issue section for a typo.
=> change error to inputError

content/docs/db.json, content/docs/testing/database_tests.md
Related to https://github.com/adonisjs/lucid/pull/988
=> Database Tests page

content/docs/security/rate-limiter.md
Hey there!
This PR replaces  blockFor to blockDuration in the docs.
=> docs(rate-limiter): replace blockFor to blockDuration in session controller

content/docs/mail/class_based_mails.md, content/docs/mail/introduction.md
Hello :wave: 
Some of the imports for email service were wrong and were using `mail` updated them to use the `main`
=> Fix wrong import for mail service

content/docs/guides/installation.md
Hi, this PR is to correct an error in the v6 installation guide. https://github.com/adonisjs/v6-docs/blob/135b5a22e996fe073fdfdd704b0f3c8e47a618b7/content/docs/guides/installation.md?plain=1#L55
=> Chore : Corrects the db from mysql to postgres

content/docs/mail/custom_transports.md
Fixed the shape of the config object for the postmark mailer. Also added the missing response argument for the MailResponse call.
=> Fixed example code for postmark transport

content/docs/experimental/vite.md
Was getting a Typescript error when following along with the docs. It looks like `reloads` should be `reload`.
=> fix: use proper reload prop name for vite config

content/docs/auth/custom_auth_guards.md
Hello, small pr just to correct some little mistakes:
- Use `E_UNAUTHORIZED_ACCESS` instead of the old way to define error
- Use the name `options` instead of `config` because you begin by using the config object but suddenly in the code you use `options` instead `config` at line 227 `jwt.sign({ userId: providerUser.getId() }, this.#options.secret)`
=> fix(custom_auth_guards): fix some small mistakes

content/docs/security/rate-limiter.md
In the section discussing Database store implementations in the Rate Limiter page, there was a reference to using Redis store instead of Database store. To maintain accuracy and clarity for users, I have corrected this discrepancy to accurately reflect the utilization of a Database store.
=> Change Redis Store to Database Store Mention

content/docs/http/routing.md
Hi,
I was searching about 404 requests in the docs and found this section:
It showed the `HttpExceptionsHandler` class but after I checked in the global exception handler, it turns out it should be `HttpExceptionHandler`. Would you mind if I just remove this single letter? Also, I changed the import to a single line.
Thank you!
=> docs: fix typo in HttpExceptionHandler class name

content/docs/http/middleware.md
Because `Module '"@adonisjs/core/http"' has no exported member 'HttpException'`
=> Fix wrong import mentioned in docs

content/docs/db.json, content/docs/digging_deeper/transmit.md
👋🏻 
This PR adds the first draft of the Transmit documentation.
The server and client documentation are currently on the same page. Let me know if you believe it makes sense to split them into two separate sections.
I have not explained how SSE works in the documentation; I believe we should also write an article and link it from the documentation for the people interested in more details.
I haven't documented events broadcasted by the `Transmit` instance. Do you believe it is a useful feature that needs documentation?
➡️ https://feat-transmit.v6-docs.pages.dev/guides/transmit
=> First draft for Transmit documentation

content/docs/digging_deeper/authorization.md
In the Bouncer docs there is mention of a `Bouncer.create` method that does not seem to exist :thinking:
I replaced the references of this method with the Bouncer constructor
=> docs: replace Bouncer.create occurences in authorization.md

content/docs/preface/introduction.md
In the [introduction page](https://docs.adonisjs.com/guides/preface/introduction#recent-releases), the link to the list of releases do not work
Putting a relative path to the .md file fixes it
=> fix: releases link

content/docs/getting_started/deployment.md
Got an error when running the server, the solution was to fix the path to be `build/bin/server.js`, then the server started properly. And if you look at the Dockerfile defined above in the page, the last line in it says `./bin/server.js`.
=> fix: path typo

content/docs/basics/exception_handling.md
In document, there's a snippet code:
```typescript
import { errors } from '@vinejs/vine'
export default class HttpExceptionHandler extends ExceptionHandler {
async handle(error: unknown, ctx: HttpContext) {
if (error instanceof errors.E_VALIDATION_EXCEPTION) {
ctx.response.status(422).send(error.messages)
return
}
return super.handle(error, ctx)
}
}
```
Actually, vine error only have `E_VALIDATION_ERROR`
=> docs: Update exception_handling.md

content/docs/security/rate_limiting.md
session.flashError as the current docs state is not a valid method. The correct method name is session.flashErrors.
=> Fix (docs): Correct method name

content/docs/authentication/verifying_user_credentials.md
The beforeSave hook has a hyperlink to a page that does not exist any more. Updating accordingly to fix issue.
=> Fix (docs): Fix broken link

templates/elements/img.edge
When using the documentation repository, I noticed that images coming from a source were not displayed.
Looking at the component, I noticed that the variable containing the URL could not be transformed, as the URL name was passed as a string.
Here's a fix that solves this problem.
=> chore: Update img.edge to fix broken image source

content/docs/views-and-templates/inertia.md
The current example throw an error `.url is not a function`.
=> Fix Dynamic root view example in Inertia

content/docs/views-and-templates/inertia.md
This PR updates the Inertia middleware example in the AdonisJS documentation: https://docs.adonisjs.com/guides/views-and-templates/inertia#share-from-a-middleware
=> Update Inertia middleware example

content/docs/references/exceptions.md
previously, the docs suggested the `@adonisjs/redis` package should be used to obtain this error, but the error actually lives in `@adonis/mail`
=> docs: update code snippet for E_MAIL_TRANSPORT_ERROR

content/docs/basics/exception_handling.md
This pull request addresses an issue in the AdonisJS documentation where the Exception class is imported redundantly from both `@adonisjs/core` and `@adonisjs/core/exceptions`. This correction streamlines the import statements across various sections of the documentation to enhance clarity and maintain consistency.
- **Clarity and Readability**: Reduces confusion by ensuring that Exception is consistently imported from the same module across the documentation.
=> Fix Redundant Exception Imports in Documentation

content/docs/getting_started/installation.md
The text says `Use the --no-install flag to create a project without installing any dependencies.` ... however that flag doesn't seem to work as they are installed anyway.
It looks like it was removed:
https://github.com/adonisjs/create-adonisjs/pull/4
=> Updated installation.md text

content/docs/digging_deeper/mail.md
Hi 👋 
Small typo mistakes here, it's `attachData` for `Buffer` and streams
=> fix(email): use attachData instead of attach

content/docs/digging_deeper/repl.md
The section `Adding custom methods to REPL` shows a snippet that is outdated, since the `--env` no exists.
```sh
node ace make:preload repl --env=repl
```
This PR replaces the above snippet by
```sh
node ace make:preload repl -e=repl
```
=> Update section "Adding custom methods to REPL" in repl.md

content/docs/authentication/session_guard.md
Hey there! 👋🏻 
This PR adds documentation about the `silent auth` middleware that we are adding back to any new installed AdonisJS 6 application using the `Session guard`.
Related https://github.com/adonisjs/presets/pull/5
=> doc(auth:session): add documentation about the silent auth middleware

content/docs/references/exceptions.md
This PR removes duplicated `E_SESSION_NOT_MUTABLE` section under `References/Exceptions`
=> fix: duplicated `E_SESSION_NOT_MUTABLE` section

content/docs/authentication/session_guard.md
The import was wrong, so I updated it to reflect the new(?) structure.
=> chore: Corrected pathname for silent_auth_middleware

content/docs/basics/session.md
This is a documentation update related to this [PR](https://github.com/adonisjs/session/pull/87).
Added support for the DynamoDB store.
=> doc(sesison): add support for DynamoDB store

content/docs/concepts/dependency_injection.md, content/docs/testing/mocks_and_fakes.md
Hello,
It seems the method to restore all fakes was incorrect + I added an example to restore multiple fakes 😁
=> docs: update restore method examples

content/docs/security/securing_ssr_applications.md
Just a little improvement for the docs to make it clear that adonis reads the `X-XSRF-Token` header when using `enableXsrfCookie`.
This was made clear in the v5 docs, but no mention of it in v6.
=> docs: Make clear which header to use for XSRF

content/docs/concepts/application_lifecycle.md
isStarted doesn't seem to exist. Shouldn't it be isReady instead?
=> docs(concepts): correct property name from isStarted to isReady

content/docs/basics/middleware.md
`server.use` was mistakenly typed as `serve.use`. 
It was just bothering me since I discovered it.
=> docs (middleware): Correct typo "serve.use" to "server.use"

content/docs/authentication/social_authentication.md
Ran into issue where the param function would only add to the request and not overwrite when already defined in the config and I need a separate auth flow. After looking around poppinss this method helped. I figure this could help others with a similar niche issue.
=> docs (social authentication): Bring to attention the clearParams method 

content/docs/views-and-templates/inertia.md
The "!" character is missing in the inertia config to specify that all routes starting by "admin" are not rendered by the server. Otherwise, it should be preferable to change the example in the "SSR Allowlist" description.
=> Correct the SSR config

assets/app.css, src/bootstrap.ts, templates/docs.edge, templates/partials/arrow.edge, templates/partials/pagination.edge
Hello 👋 
This is a PR to solve issue #34 .
I've added an edge global to handle the pagination called `getPagination` and called it inside `docs.edge` within the component pagination.
I'll share some screenshot of what it looks like.
Right now on desktop it looks like this : 
When you hover a button it gets a little bit brighter.
The main "issue" here is when text takes a lot of place it looks really tight in mobile : 
Eventually in mobile, text can be align left / right , i can edit it , here's how it looks like : 
Tell me if you've got any suggestions ! 😄
=> feat: add pagination to doc

content/docs/digging_deeper/transmit.md
This PR updates the documentation to address issues caused by GZip compression interfering with Server-Sent Events (SSE) when using `@adonisjs/transmit`. It explains how to disable GZip for the `text/event-stream` content type while keeping compression enabled for other content types. 
1. Added a new section: "Avoiding GZip Interference" in the `transmit.md` file.
2. Included configuration examples for:
- **Traefik**: Demonstrates how to use the `excludedcontenttypes` option.
=> Add GZip exclusion instructions for Transmit SSE

content/docs/ace/tui.md
I got confused why nothing was shown in my command until I realized that `.run()` was missing.
=> Update task progress

content/docs/views-and-templates/inertia.md
The examples for inertia in the documentation didn’t seem to match the project created by `npm init adonisjs@latest` . This PR fixes some of that.
=> fix: correct configuration examples in Inertia documentation

content/docs/references/exceptions.md
This adds documentation for https://github.com/adonisjs/lucid/pull/1081
=> document `error.model` in `E_ROW_NOT_FOUND`

content/docs/basics/debugging.md
Related Discussion: https://github.com/orgs/adonisjs/discussions/4844
Adding a paragraph to the Dump & Die debugging section noting that the `@dump` helper also needs an `@stack('dumper')` on the page to include its script & styles.
Related PRs:
- [Web Starter Kit](https://github.com/adonisjs/web-starter-kit/pull/16)
- [Inertia](https://github.com/adonisjs/inertia/pull/54)
=> Adding paragraph on @dump needing @stack('dumper') for script & styles

content/docs/database/redis.md
Add a section in the Redis docs and describe how to connect via unix socket.
Related: https://github.com/adonisjs/redis/issues/67
PS: I’ve enabled the checkbox to allow edits by maintainers. Please apply any changes to this PR if needed. I’m thinking of formatting or wording or a different place for the added section 🙂
=> Redis docs: add info on how to connect via unix socket

content/docs/digging_deeper/cache.md
For the cache docs, the usage example uses an invalid get or set option: `duration` 
Updated it to: `ttl`
Related type export I used to verify the correct options: 
https://github.com/Julien-R44/bentocache/blob/b739d88efabab1122706cd1bf9c38c0aa9f5fca7/packages/bentocache/src/types/options/methods_options.ts#L6-L9
=> fix: cache usage example code

assets/app.css, content/docs/authentication/social_authentication.md
Added the LinkedIn OpenID Connect configuration to the social authentication section to support the new provider created in Ally, enabling connections to LinkedIn using the OpenID Connect method.
=> feat(social authentication): added linkedin openid connect config

content/docs/views-and-templates/inertia.md
Hey folks, I was adding some lazy data eval in my project here and noticed that the method `inertia.lazy` seems to be deprecated, altough it is still being used as an example in the official docs:
=> Remove deprecated method `lazy` from inertia example

content/docs/authentication/access_tokens_guard.md
adds the `async` modifier to the function defs
Probably missed it by accident
=> doc(access-tokens): missing `async` keyword typo

content/docs/authentication/access_tokens_guard.md
Fix issues for https://github.com/adonisjs/v6-docs/pull/203 mentioned here:
https://github.com/adonisjs/v6-docs/pull/203#issuecomment-2770558740
- Correct incorrect verb in routes example:
```diff
- router.destroy('session', [SessionController, 'destroy'])
+ router.delete('session', [SessionController, 'delete'])
```
- Add note about CSRF protection
**Update:**
I added a note about the need for content negotiation in order to get appropriate responses in the case of E_INVALID_CREDENTIALS errors.
=> Auth token login

content/docs/references/events.md
Event names are currently transformed to HTML tag : https://docs.adonisjs.com/guides/references/events#cache
=> docs(cache): fix title in events references

content/docs/security/rate_limiting.md
Fixed broken links to the `adonisjs/limiter` repo by replacing `main` with `2.x`.
=> Fix broken GitHub links to adonisjs/limiter

content/docs/security/rate_limiting.md
This PR updates the documentation to mention SQLite as a supported database store option for rate limiting. It depends on the approval of PR(https://github.com/adonisjs/limiter/pull/14).
=> docs(rate-limiting): mention SQLite support for database store

content/docs/ace/prompts.md
The code snippet for `validate` accidentally used the `format` label.
=> Fix typo in prompts options table

content/docs/concepts/scaffolding.md
As seen on https://docs.adonisjs.com/guides/references/helpers#camelcase, the correct way to convert a string to CamelCase is via `string.camelCase()`, and not the wrong `string.toCamelCase()`
This is also the correct way to do things on @poppinss/string.
=> fix: Replace usages of 'string.toCamelCase()' with 'string.camelCase()'

content/docs/basics/routing.md
When reading through the routing guide on the AdonisJS website, I was confused in the grouping section because "route" was being used instead of "router." This seems like a typo to me.
=> fixed typo in routing.md documentation

content/docs/concepts/scaffolding.md
Modified the way the feature directory name is generated in the controller stub to fix the logic in the scaffolding process.
`generators.makePath()` is not a function should be `app.makePath()`
`app.makePath()` can't have another `app.makePath()` inside it
Tested it while creating this package https://github.com/adonisjs-community/modules
=> Fix scaffolding stub

content/docs/getting_started/deployment.md
The node.js in the dockerfile being 20 instead of 22 will cause applications using ally to experience errors where requests to OAuth providers hang.
=> Update deployment docs to use more recent Node.js version

content/docs/getting_started/environment_variables.md
The docs currently show this example:
```
// Mark it as optional with a condition
{
CACHE_VIEWS: Env.schema.boolean.optionalWhen(process.env.NODE_ENV === 'production')
}
```
If `NODE_ENV` is set only in `.env`, `process.env.NODE_ENV` is `undefined` when the schema is created. This makes the condition evaluate incorrectly and triggers `EnvValidationException`.
This PR updates the example to use the function form, which defers evaluation until after `.env` is loaded:
```
// Mark it as optional with a condition
{
CACHE_VIEWS: Env.schema.boolean.optionalWhen(() => process.env.NODE_ENV === 'production')
}
```
=> fix optionalWhen example
