content/docs/guides/installation.md
=> docs(Installation): missing @latest in npm init command

content/docs/http/response.md, content/docs/http/routing.md
=> Correct router typos

content/docs/digging_deeper/authorization.md
[https://github.com/adonisjs/v6-docs/issues/8](https://github.com/adonisjs/v6-docs/issues/8)
I updated .accessDenied() to .forbidden() on response in the documentation (https://docs.adonisjs.com/guides/authorization)
Resolves #8
=> Updated .accessDenied() to .forbidden() on response

content/docs/auth/introduction.md, content/docs/database/redis.md, content/docs/digging_deeper/authorization.md, content/docs/digging_deeper/i18n.md, content/docs/digging_deeper/social_auth.md, content/docs/http/assets_bundling.md, content/docs/http/session.md, content/docs/http/static_file_server.md, content/docs/http/validation.md, content/docs/http/views_and_templates.md, content/docs/mail/introduction.md, content/docs/reference/commands.md, content/docs/security/cors.md, content/docs/security/rate-limiter.md, content/docs/security/web-security.md
- added it in the commands reference
- i also migrated the auth installation documentation from `configure` to `add`. Just that one for now. if it looks ok, then I'll migrate everything else. I would rather be sure before doing the rest because it's going to be a bit long  😁
=> Documentation for new `ace add` command

content/docs/http/exception_handling.md
updated the typo in the `Create Exception report function`
=> fix: Update exception_handling.md for typo

content/docs/db.json, content/docs/digging_deeper/locks.md
we are going to miss a lot of stuff from the Verrou documentation. but, i think that will be enough: we are redirecting people to the Verrou documentation for more details.
i think the essentials are covered, but let me know if there's anything you think should be mentioned here too
Preview : https://feat-locks-doc.v6-docs.pages.dev/guides/locks
=> feat: Locks documentation

content/docs/testing/http_tests.md
Hi 👋 
Thanks for your awesome project and documentation 👌 
I found some missing `async` in the examples. Hope it'll help 🙏
=> fix(http_tests): missing some async

content/docs/experimental/inertia.md
=> fix: bug on page inertia, section on this page

content/docs/experimental/inertia.md, content/docs/experimental/vite.md, content/docs/fundamentals/package_development.md, content/docs/guides/installation.md, content/docs/http/assets_bundling_encore.md, content/docs/testing/browser_tests.md, content/docs/testing/http_tests.md
Fix this issue https://github.com/adonisjs/v6-docs/issues/73
=> fix: remove keyword latest to yarn setup command

content/docs/db.json, content/docs/fundamentals/hmr.md
https://feat-hmr-docs.v6-docs.pages.dev/guides/hot-module-reloading
=> feat: hmr docs

content/docs/fundamentals/scaffolding.md, content/docs/reference/commands.md, content/releases.json
Documentation for https://github.com/adonisjs/core/pull/4533
=> feat: document env:add and defineEnvVariables new option

assets/app.css
=> Improve styles of scrollbars in dark theme

content/docs/security/authorization.md
Apologies if this is incorrect. I’m new to Adonis and backend in general, but I was reading through the docs and it looked as though the method names were incorrect…
=> Fix incorrect method names

content/docs/experimental/inertia.md
Fix destructuring parameter in  the redirects section of inertia
=> fix(docs) update destructuring parameters

content/docs/concepts/dependency_injection.md
Changing URL point to `The container README file`
=> docs: Update dependency_injection.md

content/docs/digging_deeper/logger.md
Close #109 
I'm linking to the repo that contains the specification because it's a bit of a mess with the sites as far as I can see.
See https://github.com/ndjson/ndjson.github.io/issues/24
=> Bad link in the documentation to a Korean sports gambling site

content/docs/views-and-templates/inertia.md
Replace a link in the Inertia page.
=> fix(views-and-templates:inertia): replace bad link to correct one

content/docs/basics/controllers.md
I think the description of the resource.except method is wrong. Please let me know if I've made a mistake.
=> docs: update resource.except method description

content/docs/preface/introduction.md
=> docs: fix import syntax

content/docs/basics/response.md
Documentation for https://github.com/adonisjs/http-server/pull/96
=> doc(basics:response): add request-id

content/docs/getting_started/deployment.md
Tiny fix for the warning block.
=> fix: correct warning block

content/docs/authentication/basic_auth_guard.md, content/docs/authentication/session_guard.md
=> Fix outdated links to E_UNAUTHORIZED_ACCESS in session and basic auth guides

content/docs/getting_started/environment_variables.md
Hey there! 👋🏻 
This PR documents the new method from https://github.com/adonisjs/env/pull/44
It should be merged once a new version of the `@adonisjs/env` module is released.
=> doc(env): add defineIdentifier

content/docs/authentication/access_tokens_guard.md
Implemented by https://github.com/adonisjs/auth/pull/251
I have yet to ensure that the examples work when copied verbatim, but I think the content is ready for review.
=> Document access tokens guard methods: createToken, invalidateToken

content/docs/concepts/http_overview.md
Changing relative pronouns from *who* to *which* (referring to things).
=> Fix relative pronouns
